version: '3.8'
services:

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment: 
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=my-database
    volumes: 
    - postgres-data:/var/lib/postgresql/data
    ports: 
    - "5432:5432"
    networks:
    - postgres-network
    profiles: ['db']
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
    - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    ports:
    - "15432:80"
    networks:
    - postgres-network
    profiles: ['db']

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data: