apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: postgres
spec:
  storageClassName: local-storage
  # storageClassName: aws-storage
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/data"
  capacity:
    storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  storageClassName: local-storage
  # storageClassName: aws-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi